version: '2.15'
services:
api:
 # image: pankaj/nestjs/graphql
 build:
 dockerfile: Dockerfile
 context: .
 depends_on:
  -postgres
 environment:
  DATABASE_URL: postgres://user:password@postgres:5432/db
  NODE_ENV: development
  PORT: 3004
  ports:
   -"8080:3004"
  postgres:
     image: postgres:10.4
     ports:
       -"35000:5432"
     environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password
     POSTGRES_DB: db

